#!/bin/bash
# aastaaja kontroll vastavalt kuule
# skripti algus

# küsib kuu numbrit
read -p "Sisesta kuu number: " kuu

# väljastab aastaaja vastavalt numbrile
if (( kuu >= 3 && kuu <= 5 )); then
    echo "Praegu on kevad"
elif (( kuu >= 6 && kuu <= 8 )); then
    echo "Praegu on suvi"
elif (( kuu >= 9 && kuu <= 11 )); then
    echo "Praegu on sügis"
elif (( kuu == 1 || kuu == 2 || kuu == 12 )); then
    echo "Praegu on talv"
else
    echo "Sisestatud arv pole sobilik"
fi

